#!/bin/bash
#--------------------Author:ekahPruthvi--------------------#

#-----------------init------------------------#
cd ~/
flag=1

#-----------------files&folders---------------#
fnf() {
    local hide="$1"
    if [ "$hide" = 1 ]; then
        folders=$(ls -d */)
        files=$(ls -p | grep -v /)
    else
        folders=$(ls -Ap | grep / | grep "^.")
        files=$(ls -Ap | grep -v / | grep "^.")
    fi
}

#--------------------icons--------------------#
showfile(){
    fnf "$flag"
    readarray -t file_array <<<"$files"

    local num=${#file_array[@]}
    local win_width=$(tput cols)
    local max_lines=$(( (num / (win_width / 15)) + 1 ))
    local cur_num=$num
    local files_in_line=$(( (win_width / 15) - 1 ))

    printf "[$PWD]\n\n"
    printf "$win_width\n$max_lines\n$num\n" #testing 
    if [[ $(( win_width / 15 )) -gt "$num"  ]]; then 
        for word in "${file_array[@]}"; do
            printf  "╔█▀▀▀▀▀▄\t"
        done
        echo 
        for word in "${file_array[@]}"; do
            printf  "║█     █\t"
        done
        echo
        for word in "${file_array[@]}"; do
            printf  "║█#####█\t"
        done
        echo
        for word in "${file_array[@]}"; do
            printf  "║█▄▄▄▄▄█\t"
        done
        echo
        for word in "${file_array[@]}"; do
            printf  "╚══════╝\t"
        done
        echo
        for word in "${file_array[@]}"; do
            printf  "%-15.15s " "-$word"
        done
    else 
        local start=0
        local start_wc=0
        local w=0
        local wc=0
        for (( i=1 ; i<=$max_lines ; i++ )); do
            w=$start
            wc=$start_wc
            while [ $w -lt $files_in_line ] && [ $wc -lt $num ]; do
                printf  "╔█▀▀▀▀▀▄\t"
                ((w++))
                ((wc++))
            done
            echo
            w=$start
            wc=$start_wc
            while [ $w -lt $files_in_line ] && [ $wc -lt $num ]; do
                printf  "║█     █\t"
                ((w++))
                ((wc++))
            done
            echo
            w=$start
            wc=$start_wc
            while [ $w -lt $files_in_line ] && [ $wc -lt $num ]; do
                printf  "║█#####█\t"
                ((w++))
                ((wc++))
            done
            echo
            w=$start
            wc=$start_wc
            while [ $w -lt $files_in_line ] && [ $wc -lt $num ]; do
                printf  "║█▄▄▄▄▄█\t"
                ((w++))
                ((wc++))
            done
            echo
            w=$start
            wc=$start_wc
            while [ $w -lt $files_in_line ] && [ $wc -lt $num ]; do
                printf  "╚══════╝\t"
                ((w++))
                ((wc++))
            done
            echo
            w=$start
            wc=$start_wc
            while [ $w -lt $files_in_line ] && [ $wc -lt $num ]; do
                printf  "%-15.15s " "-${file_array[$wc]}"
                ((w++))
                ((wc++))
            done
            #echo "$w $files_in_line $wc $num" #testing
            w=0
            start_wc=$wc
            start=$w
            echo 
            echo
        done
    fi

}

#--------------------menu--------------------#
while true; do
    read -rsn1 input
    if [ "$input" = "a" ]; then
        clear
        showfile
    elif [ "$input" = "h" ]; then
        clear
        if [[ "$flag" -eq 1 ]]; then
            echo "hide toggle off"
            flag=0
        else
            echo "hide toggle on"
            flag=1
        fi
    elif [ "$input" = "s" ]; then
        clear
        read -s complete
        echo "$complete"
    elif [ "$input" = "q" ]; then
        clear
        break
    fi
done